import { useState } from 'react'
import { jsPDF } from 'jspdf'
import Button from './Button'

export default function OutputPanel({ result, model, tokens }) {
  const [copied, setCopied] = useState(false)

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(result)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      alert('Copy failed — please select and copy the text manually.')
    }
  }

  const handleDownloadPDF = () => {
    const doc = new jsPDF({ unit: 'mm', format: 'a4' })
    const pageWidth = doc.internal.pageSize.getWidth()
    const margin = 18
    const usableWidth = pageWidth - margin * 2

    // Header band
    doc.setFillColor(108, 77, 246)
    doc.rect(0, 0, pageWidth, 28, 'F')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(16)
    doc.setTextColor(255, 255, 255)
    doc.text('Simplified Discharge Summary', margin, 17)

    // Sub-header
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.setTextColor(220, 210, 255)
    const dateStr = new Date().toLocaleDateString('en-IN', {
      day: '2-digit',
      month: 'long',
      year: 'numeric',
    })
    doc.text(`Generated by MedSimplify  ·  ${dateStr}  ·  Model: ${model || 'N/A'}`, margin, 24)

    // Body text
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(11)
    doc.setTextColor(30, 30, 50)
    const lines = doc.splitTextToSize(result, usableWidth)
    doc.text(lines, margin, 40)

    // Footer
    const pageHeight = doc.internal.pageSize.getHeight()
    doc.setFontSize(8)
    doc.setTextColor(160, 160, 180)
    doc.text(
      'For medical guidance, always consult a qualified healthcare professional.  |  For research use only.',
      margin,
      pageHeight - 10
    )

    doc.save('simplified_discharge_summary.pdf')
  }

  // Empty state
  if (!result) {
    return (
      <div className="flex-1 rounded-xl border-2 border-dashed border-gray-200 flex flex-col items-center justify-center min-h-[220px] gap-3 text-gray-400">
        <span className="text-4xl">📄</span>
        <p className="text-sm">Your simplified summary will appear here…</p>
      </div>
    )
  }

  return (
    <div className="flex flex-col gap-3">
      {/* Meta bar */}
      <div className="flex items-center justify-between flex-wrap gap-2">
        <div className="flex items-center gap-2 flex-wrap">
          {model && (
            <span className="bg-primary-50 text-primary-500 text-xs font-semibold px-3 py-1 rounded-full">
              🤖 {model}
            </span>
          )}
          {tokens && (
            <span className="text-xs text-gray-400">{tokens} tokens</span>
          )}
        </div>
        <div className="flex gap-2">
          <Button variant="outline" className="py-1.5 px-3 text-xs" onClick={handleCopy}>
            {copied ? '✓ Copied' : '📋 Copy'}
          </Button>
          <Button variant="primary" className="py-1.5 px-3 text-xs" onClick={handleDownloadPDF}>
            ⬇ Download PDF
          </Button>
        </div>
      </div>

      {/* Result text */}
      <div className="bg-gray-50 rounded-xl border border-gray-200 p-5 text-sm text-gray-700 leading-relaxed whitespace-pre-wrap max-h-[480px] overflow-y-auto">
        {result}
      </div>
    </div>
  )
}
