import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:flutter_markdown/flutter_markdown.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:provider/provider.dart';
import 'package:printing/printing.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../models/api_model.dart';
import '../models/simplify_result.dart';
import '../services/simplify_service.dart';
import '../services/storage_service.dart';
import '../theme/app_theme.dart';
import '../widgets/app_drawer.dart';
import '../widgets/chat_panel.dart';
import '../widgets/loading_overlay.dart';
import '../widgets/model_selector.dart';
import 'result_screen.dart';
import 'settings_screen.dart';

class HomeScreen extends StatefulWidget {
  final VoidCallback onToggleTheme;
  final bool isDark;

  const HomeScreen({
    super.key,
    required this.onToggleTheme,
    required this.isDark,
  });

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  final _textController = TextEditingController();
  final _scrollController = ScrollController();

  ApiModel _selectedModel = ApiModel.all.first;
  // Default prompting strategy is few-shot
  final String _strategy = 'few-shot';
  bool _loading = false;
  String? _error;
  SimplifyResult? _result;

  @override
  void initState() {
    super.initState();
    _loadPreferences();
  }

  Future<void> _loadPreferences() async {
    final storage = context.read<StorageService>();
    final savedModelId = storage.lastModelId;
    final model = ApiModel.all.firstWhere(
      (m) => m.id == savedModelId,
      orElse: () => ApiModel.all.first,
    );
    setState(() {
      _selectedModel = model;
    });
  }

  Future<void> _simplify() async {
    final text = _textController.text.trim();
    if (text.isEmpty) {
      setState(() => _error = 'Please paste a discharge summary first.');
      return;
    }

    final storage = context.read<StorageService>();

    // Check API key exists for selected model
    final hasKey = switch (_selectedModel.provider) {
      'cerebras' => storage.cerebrasKey.isNotEmpty,
      'gemini' => storage.geminiKey.isNotEmpty,
      'groq' => storage.groqKey.isNotEmpty,
      _ => false,
    };

    if (!hasKey) {
      setState(() => _error =
          'No API key configured for ${_selectedModel.providerLabel}. Add it in Settings.');
      return;
    }

    setState(() {
      _loading = true;
      _error = null;
      _result = null;
    });

    // Save preferences
    await storage.setLastModelId(_selectedModel.id);
    await storage.setLastStrategy(_strategy);

    try {
      final svc = SimplifyService(storage);
      final result = await svc.simplify(
        rawText: text,
        model: _selectedModel,
        strategy: _strategy,
      );
      setState(() => _result = result);
    } catch (e) {
      setState(() => _error = e.toString().replaceFirst('Exception: ', ''));
    } finally {
      setState(() => _loading = false);
    }
  }

  void _clearAll() {
    _textController.clear();
    setState(() {
      _result = null;
      _error = null;
    });
  }

  Future<void> _downloadPdf(SimplifyResult res) async {
    final doc = pw.Document();
    final dateStr =
        '${res.timestamp.day}/${res.timestamp.month}/${res.timestamp.year}';

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (_) => pw.Container(
          padding: const pw.EdgeInsets.only(bottom: 12),
          decoration: const pw.BoxDecoration(
            border: pw.Border(
              bottom: pw.BorderSide(color: PdfColor.fromInt(0xFF6C4DF6), width: 2),
            ),
          ),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'Simplified Discharge Summary',
                style: const pw.TextStyle(
                  fontSize: 20,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColor.fromInt(0xFF6C4DF6),
                ),
              ),
              pw.SizedBox(height: 4),
              pw.Text(
                'Generated by MedSimplify Lite  ·  $dateStr  ·  Model: ${res.modelName}',
                style: const pw.TextStyle(
                    fontSize: 9, color: PdfColor.fromInt(0xFF8B949E)),
              ),
            ],
          ),
        ),
        footer: (_) => pw.Container(
          alignment: pw.Alignment.center,
          padding: const pw.EdgeInsets.only(top: 12),
          child: pw.Text(
            'For medical guidance, always consult a qualified healthcare professional.  |  For research use only.',
            style: const pw.TextStyle(
                fontSize: 8, color: PdfColor.fromInt(0xFF8B949E)),
            textAlign: pw.TextAlign.center,
          ),
        ),
        build: (_) => [
          pw.Text(
            res.simplifiedText,
            style: const pw.TextStyle(fontSize: 11, lineSpacing: 5),
          ),
        ],
      ),
    );

    await Printing.layoutPdf(
      onLayout: (_) async => doc.save(),
      name: 'simplified_discharge_summary.pdf',
    );
  }

  @override
  void dispose() {
    _textController.dispose();
    _scrollController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final isDark = widget.isDark;
    final bgColor = isDark ? AppTheme.bgDark : AppTheme.bgLight;
    final cardColor = isDark ? AppTheme.cardDark : AppTheme.cardLight;
    final borderColor = isDark ? AppTheme.borderDark : AppTheme.borderLight;
    final textColor =
        isDark ? AppTheme.textPrimaryDark : AppTheme.textPrimaryLight;
    final subColor =
        isDark ? AppTheme.textSecondaryDark : AppTheme.textSecondaryLight;

    final screenWidth = MediaQuery.of(context).size.width;
    final isThreeColumn = screenWidth >= 1180;
    final isTwoColumn = screenWidth >= 800 && screenWidth < 1180;

    return Scaffold(
      backgroundColor: bgColor,
      drawer: AppDrawer(
        isDark: isDark,
        onToggleTheme: widget.onToggleTheme,
      ),
      appBar: AppBar(
        backgroundColor: isDark ? AppTheme.surfaceDark : AppTheme.surfaceLight,
        title: Row(
          children: [
            Container(
              width: 32,
              height: 32,
              decoration: BoxDecoration(
                gradient: const LinearGradient(
                  colors: [Color(0xFF6C4DF6), Color(0xFF9B7FFF)],
                  begin: Alignment.topLeft,
                  end: Alignment.bottomRight,
                ),
                borderRadius: BorderRadius.circular(10),
              ),
              child: const Icon(Icons.medical_services_rounded,
                  color: Colors.white, size: 18),
            ),
            const SizedBox(width: 10),
            Text(
              'MedSimplify',
              style: GoogleFonts.inter(
                fontWeight: FontWeight.w800,
                fontSize: 18,
                color: textColor,
              ),
            ),
            const SizedBox(width: 16),
            // ── In-Navbar Research Use Disclaimer Chip ──
            Flexible(
              child: Container(
                padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 5),
                decoration: BoxDecoration(
                  color: isDark
                      ? const Color(0xFF1E2A4A)
                      : const Color(0xFFEFF6FF),
                  borderRadius: BorderRadius.circular(20),
                  border: Border.all(
                    color: isDark
                        ? const Color(0xFF2D4080)
                        : const Color(0xFFBFDBFE),
                  ),
                ),
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    const Icon(Icons.info_outline_rounded,
                        size: 14, color: Color(0xFF3B82F6)),
                    const SizedBox(width: 6),
                    Flexible(
                      child: Text(
                        screenWidth > 600
                            ? 'For Research Use Only · Always Consult a Healthcare Professional'
                            : 'Research Use Only',
                        style: GoogleFonts.inter(
                          fontSize: 11,
                          fontWeight: FontWeight.w500,
                          color: isDark
                              ? const Color(0xFF93C5FD)
                              : const Color(0xFF1E40AF),
                        ),
                        overflow: TextOverflow.ellipsis,
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
        actions: [
          IconButton(
            icon: Icon(
              isDark ? Icons.light_mode_rounded : Icons.dark_mode_rounded,
              color: subColor,
            ),
            tooltip: isDark ? 'Light mode' : 'Dark mode',
            onPressed: widget.onToggleTheme,
          ),
          IconButton(
            icon: Icon(Icons.settings_rounded, color: subColor),
            tooltip: 'Settings',
            onPressed: () => Navigator.push(
              context,
              MaterialPageRoute(builder: (_) => const SettingsScreen()),
            ),
          ),
        ],
        bottom: PreferredSize(
          preferredSize: const Size.fromHeight(1),
          child: Divider(height: 1, color: borderColor),
        ),
      ),
      body: SingleChildScrollView(
        controller: _scrollController,
        padding: EdgeInsets.symmetric(
          horizontal: isThreeColumn ? 24 : (screenWidth > 600 ? 20 : 12),
          vertical: 16,
        ),
        child: Center(
          child: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 1600),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // ── Page header ───────────────────────────────────────────────
                Row(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            'Discharge Summary Simplifier & Assistant',
                            style: GoogleFonts.inter(
                              fontSize: isThreeColumn ? 22 : 18,
                              fontWeight: FontWeight.w800,
                              color: textColor,
                            ),
                          ).animate().fadeIn(duration: 300.ms).slideX(begin: -0.02),
                          const SizedBox(height: 4),
                          Text(
                            'Enter your clinical summary to generate an Indian Lay English explanation and chat in real-time with the health assistant.',
                            style: GoogleFonts.inter(
                                fontSize: 13, color: subColor, height: 1.4),
                          ).animate().fadeIn(delay: 100.ms, duration: 300.ms),
                        ],
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 18),

                // ── 3-Card Layout ─────────────────────────────────────────────
                if (isThreeColumn) ...[
                  // 3 Columns Side-by-Side
                  IntrinsicHeight(
                    child: Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        // Card 1: Input
                        Expanded(
                          flex: 3,
                          child: _buildInputCard(cardColor, borderColor,
                              textColor, subColor, isDark),
                        ),
                        const SizedBox(width: 16),
                        // Card 2: Simplified Summary
                        Expanded(
                          flex: 4,
                          child: _buildSummaryCard(cardColor, borderColor,
                              textColor, subColor, isDark),
                        ),
                        const SizedBox(width: 16),
                        // Card 3: Chatbot Assistant
                        Expanded(
                          flex: 4,
                          child: _buildChatCard(cardColor, borderColor,
                              textColor, subColor, isDark),
                        ),
                      ],
                    ),
                  ),
                ] else if (isTwoColumn) ...[
                  // 2 Columns: Input on Left, Summary + Chat Stacked on Right
                  IntrinsicHeight(
                    child: Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Expanded(
                          flex: 4,
                          child: _buildInputCard(cardColor, borderColor,
                              textColor, subColor, isDark),
                        ),
                        const SizedBox(width: 16),
                        Expanded(
                          flex: 5,
                          child: Column(
                            children: [
                              _buildSummaryCard(cardColor, borderColor,
                                  textColor, subColor, isDark),
                              const SizedBox(height: 16),
                              _buildChatCard(cardColor, borderColor,
                                  textColor, subColor, isDark),
                            ],
                          ),
                        ),
                      ],
                    ),
                  ),
                ] else ...[
                  // Mobile Single Column Stack
                  _buildInputCard(
                      cardColor, borderColor, textColor, subColor, isDark),
                  const SizedBox(height: 16),
                  _buildSummaryCard(
                      cardColor, borderColor, textColor, subColor, isDark),
                  const SizedBox(height: 16),
                  _buildChatCard(
                      cardColor, borderColor, textColor, subColor, isDark),
                ],

                const SizedBox(height: 30),
              ],
            ),
          ),
        ),
      ),
    );
  }

  // ── CARD 1: INPUT ───────────────────────────────────────────────────────────
  Widget _buildInputCard(Color cardColor, Color borderColor, Color textColor,
      Color subColor, bool isDark) {
    final wordCount = _textController.text
        .trim()
        .split(RegExp(r'\s+'))
        .where((w) => w.isNotEmpty)
        .length;

    return Container(
      padding: const EdgeInsets.all(18),
      decoration: BoxDecoration(
        color: cardColor,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: borderColor),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Header
          Row(
            children: [
              Container(
                width: 26,
                height: 26,
                decoration: BoxDecoration(
                  color: const Color(0xFF6C4DF6).withValues(alpha: 0.12),
                  borderRadius: BorderRadius.circular(8),
                ),
                child: const Icon(Icons.edit_note_rounded,
                    size: 16, color: Color(0xFF6C4DF6)),
              ),
              const SizedBox(width: 8),
              Text(
                '1. INPUT SUMMARY',
                style: GoogleFonts.inter(
                  fontSize: 12,
                  fontWeight: FontWeight.w700,
                  color: textColor,
                  letterSpacing: 0.6,
                ),
              ),
              const Spacer(),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                decoration: BoxDecoration(
                  color: const Color(0xFF10B981).withValues(alpha: 0.1),
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Text(
                  'Few-shot Active',
                  style: GoogleFonts.inter(
                    fontSize: 10,
                    fontWeight: FontWeight.w600,
                    color: const Color(0xFF10B981),
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 14),

          // Model selector
          ModelSelector(
            selected: _selectedModel,
            models: ApiModel.all,
            onChanged: (m) => setState(() => _selectedModel = m),
          ),
          const SizedBox(height: 14),

          /*
          // NOTE: Prompting Strategy choice commented out per requirement. Defaulted to few-shot.
          StrategySelector(
            selected: _strategy,
            onChanged: (s) => setState(() => _strategy = s),
          ),
          const SizedBox(height: 14),
          */

          // Text area
          Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                'CLINICAL DISCHARGE TEXT',
                style: GoogleFonts.inter(
                  fontSize: 11,
                  fontWeight: FontWeight.w600,
                  color: subColor,
                  letterSpacing: 0.6,
                ),
              ),
              const SizedBox(height: 6),
              TextField(
                controller: _textController,
                maxLines: 10,
                onChanged: (_) => setState(() {}),
                style: GoogleFonts.inter(
                    fontSize: 13, color: textColor, height: 1.5),
                decoration: InputDecoration(
                  hintText:
                      'Paste the patient\'s discharge summary here…\n\nExample: The patient was admitted with chest pain, ST-elevation on ECG, Troponin positive…',
                  hintStyle: GoogleFonts.inter(
                      fontSize: 12,
                      color: subColor.withValues(alpha: 0.7),
                      height: 1.5),
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(12),
                    borderSide: BorderSide(color: borderColor),
                  ),
                  enabledBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(12),
                    borderSide: BorderSide(color: borderColor),
                  ),
                  focusedBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(12),
                    borderSide: const BorderSide(
                        color: AppTheme.primaryIndigo, width: 2),
                  ),
                  filled: true,
                  fillColor: isDark
                      ? AppTheme.bgDark
                      : AppTheme.bgLight,
                  contentPadding: const EdgeInsets.all(12),
                ),
              ),
              const SizedBox(height: 4),
              Align(
                alignment: Alignment.centerRight,
                child: Text(
                  '$wordCount words',
                  style: GoogleFonts.inter(
                      fontSize: 11, color: subColor.withValues(alpha: 0.7)),
                ),
              ),
            ],
          ),

          // Error
          if (_error != null) ...[
            const SizedBox(height: 10),
            Container(
              padding: const EdgeInsets.all(10),
              decoration: BoxDecoration(
                color: const Color(0xFFFEF2F2),
                borderRadius: BorderRadius.circular(10),
                border: Border.all(color: const Color(0xFFFECACA)),
              ),
              child: Row(
                children: [
                  const Icon(Icons.error_outline_rounded,
                      color: Color(0xFFEF4444), size: 16),
                  const SizedBox(width: 6),
                  Expanded(
                    child: Text(
                      _error!,
                      style: GoogleFonts.inter(
                          fontSize: 12, color: const Color(0xFFDC2626)),
                    ),
                  ),
                ],
              ),
            ),
          ],

          const SizedBox(height: 14),
          // Buttons
          Row(
            children: [
              Expanded(
                child: ElevatedButton.icon(
                  onPressed: _loading ? null : _simplify,
                  icon: _loading
                      ? const SizedBox(
                          width: 15,
                          height: 15,
                          child: CircularProgressIndicator(
                            strokeWidth: 2,
                            color: Colors.white,
                          ),
                        )
                      : const Icon(Icons.auto_fix_high_rounded, size: 16),
                  label: Text(_loading ? 'Simplifying…' : '✨ Simplify Summary'),
                  style: ElevatedButton.styleFrom(
                    padding: const EdgeInsets.symmetric(vertical: 12),
                  ),
                ),
              ),
              if (_textController.text.isNotEmpty || _result != null) ...[
                const SizedBox(width: 8),
                OutlinedButton(
                  onPressed: _clearAll,
                  style: OutlinedButton.styleFrom(
                    padding: const EdgeInsets.symmetric(
                        vertical: 12, horizontal: 14),
                  ),
                  child: const Text('Clear'),
                ),
              ],
            ],
          ),
        ],
      ),
    ).animate().fadeIn(duration: 250.ms);
  }

  // ── CARD 2: SIMPLIFIED SUMMARY ──────────────────────────────────────────────
  Widget _buildSummaryCard(Color cardColor, Color borderColor, Color textColor,
      Color subColor, bool isDark) {
    return Container(
      padding: const EdgeInsets.all(18),
      decoration: BoxDecoration(
        color: cardColor,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: borderColor),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Header
          Row(
            children: [
              Container(
                width: 26,
                height: 26,
                decoration: BoxDecoration(
                  color: const Color(0xFF10B981).withValues(alpha: 0.12),
                  borderRadius: BorderRadius.circular(8),
                ),
                child: const Icon(Icons.description_rounded,
                    size: 16, color: Color(0xFF10B981)),
              ),
              const SizedBox(width: 8),
              Text(
                '2. SIMPLIFIED SUMMARY',
                style: GoogleFonts.inter(
                  fontSize: 12,
                  fontWeight: FontWeight.w700,
                  color: textColor,
                  letterSpacing: 0.6,
                ),
              ),
              const Spacer(),
              if (_result != null) ...[
                IconButton(
                  icon: Icon(Icons.copy_rounded, size: 16, color: subColor),
                  tooltip: 'Copy',
                  onPressed: () async {
                    await Clipboard.setData(
                        ClipboardData(text: _result!.simplifiedText));
                    if (mounted) {
                      ScaffoldMessenger.of(context).showSnackBar(
                        const SnackBar(
                            content: Text('Copied to clipboard ✓'),
                            duration: Duration(seconds: 1)),
                      );
                    }
                  },
                ),
                IconButton(
                  icon: Icon(Icons.picture_as_pdf_rounded,
                      size: 16, color: subColor),
                  tooltip: 'PDF Export',
                  onPressed: () => _downloadPdf(_result!),
                ),
                IconButton(
                  icon: Icon(Icons.open_in_full_rounded,
                      size: 16, color: subColor),
                  tooltip: 'Full Screen',
                  onPressed: () => Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (_) => ResultScreen(result: _result!),
                    ),
                  ),
                ),
              ],
            ],
          ),
          const SizedBox(height: 10),
          Divider(height: 1, color: borderColor),
          const SizedBox(height: 12),

          if (_loading)
            const SizedBox(
              height: 320,
              child: LoadingOverlay(
                message: 'Simplifying discharge summary…',
              ),
            )
          else if (_result != null) ...[
            // Model meta bar
            Row(
              children: [
                Container(
                  padding:
                      const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                  decoration: BoxDecoration(
                    color: const Color(0xFF6C4DF6).withValues(alpha: 0.12),
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: Text(
                    '🤖 ${_result!.modelName}',
                    style: GoogleFonts.inter(
                      fontSize: 11,
                      fontWeight: FontWeight.w600,
                      color: const Color(0xFF6C4DF6),
                    ),
                  ),
                ),
                if (_result!.tokensUsed != null) ...[
                  const SizedBox(width: 8),
                  Text(
                    '${_result!.tokensUsed} tokens',
                    style: GoogleFonts.inter(fontSize: 11, color: subColor),
                  ),
                ],
              ],
            ),
            const SizedBox(height: 10),
            // Markdown text
            Container(
              constraints: const BoxConstraints(minHeight: 220, maxHeight: 380),
              child: Scrollbar(
                thumbVisibility: true,
                child: SingleChildScrollView(
                  child: MarkdownBody(
                    data: _result!.simplifiedText,
                    styleSheet: MarkdownStyleSheet(
                      p: GoogleFonts.inter(
                          fontSize: 13.5, color: textColor, height: 1.65),
                      strong: GoogleFonts.inter(
                          fontSize: 13.5,
                          fontWeight: FontWeight.w600,
                          color: textColor),
                    ),
                  ),
                ),
              ),
            ),
          ] else ...[
            // Empty state
            Container(
              height: 280,
              decoration: BoxDecoration(
                color: isDark ? AppTheme.bgDark : AppTheme.bgLight,
                borderRadius: BorderRadius.circular(12),
                border: Border.all(color: borderColor),
              ),
              child: Center(
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Icon(Icons.auto_awesome_rounded,
                        size: 36, color: subColor.withValues(alpha: 0.35)),
                    const SizedBox(height: 10),
                    Text(
                      'Simplified summary will appear here',
                      style: GoogleFonts.inter(
                          fontSize: 13,
                          fontWeight: FontWeight.w500,
                          color: subColor),
                    ),
                    const SizedBox(height: 4),
                    Text(
                      'Paste text in Card 1 and tap Simplify',
                      style: GoogleFonts.inter(
                          fontSize: 11,
                          color: subColor.withValues(alpha: 0.7)),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ],
      ),
    ).animate().fadeIn(duration: 250.ms, delay: 50.ms);
  }

  // ── CARD 3: CHATBOT ASSISTANT ───────────────────────────────────────────────
  Widget _buildChatCard(Color cardColor, Color borderColor, Color textColor,
      Color subColor, bool isDark) {
    if (_result != null) {
      return ChatPanel(
        result: _result!,
        model: _selectedModel,
        isCompact: false,
      ).animate().fadeIn(duration: 250.ms, delay: 100.ms);
    }

    return Container(
      padding: const EdgeInsets.all(18),
      decoration: BoxDecoration(
        color: cardColor,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: borderColor),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Container(
                width: 26,
                height: 26,
                decoration: BoxDecoration(
                  color: const Color(0xFFF59E0B).withValues(alpha: 0.12),
                  borderRadius: BorderRadius.circular(8),
                ),
                child: const Icon(Icons.forum_rounded,
                    size: 16, color: Color(0xFFF59E0B)),
              ),
              const SizedBox(width: 8),
              Text(
                '3. MEDICAL ASSISTANT',
                style: GoogleFonts.inter(
                  fontSize: 12,
                  fontWeight: FontWeight.w700,
                  color: textColor,
                  letterSpacing: 0.6,
                ),
              ),
            ],
          ),
          const SizedBox(height: 10),
          Divider(height: 1, color: borderColor),
          const SizedBox(height: 12),
          Container(
            height: 330,
            decoration: BoxDecoration(
              color: isDark ? AppTheme.bgDark : AppTheme.bgLight,
              borderRadius: BorderRadius.circular(12),
              border: Border.all(color: borderColor),
            ),
            child: Center(
              child: Padding(
                padding: const EdgeInsets.all(24),
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Container(
                      width: 44,
                      height: 44,
                      decoration: BoxDecoration(
                        gradient: const LinearGradient(
                          colors: [Color(0xFF6C4DF6), Color(0xFF9B7FFF)],
                          begin: Alignment.topLeft,
                          end: Alignment.bottomRight,
                        ),
                        borderRadius: BorderRadius.circular(12),
                      ),
                      child: const Icon(Icons.smart_toy_rounded,
                          size: 24, color: Colors.white),
                    ),
                    const SizedBox(height: 14),
                    Text(
                      'Chatbot Ready on Generation',
                      style: GoogleFonts.inter(
                          fontSize: 14,
                          fontWeight: FontWeight.w600,
                          color: textColor),
                    ),
                    const SizedBox(height: 6),
                    Text(
                      'Once your discharge summary is simplified, you can ask follow-up questions about medicines, diet, precautions, and warning signs right here.',
                      style: GoogleFonts.inter(
                          fontSize: 12, color: subColor, height: 1.45),
                      textAlign: TextAlign.center,
                    ),
                  ],
                ),
              ),
            ),
          ),
        ],
      ),
    ).animate().fadeIn(duration: 250.ms, delay: 100.ms);
  }
}
